Fix ImportError: cannot import name 'Callable' from 'collections' for Python 3.10+
In Python 3.10 the Callable class has been moved to the collections.abc module.